name: CI/CD for AWS Lambda

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy lambda_function.py
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Package Lambda function
        run: |
          zip -r lambda_function.zip .

      - name: Configure AWS credentials and deploy Lambda function
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ap-south-1
        run: |
          aws lambda update-function-code \
            --function-name lambda_function \
            --zip-file fileb://lambda_function.zip \
            --region $ap-south-1 \
            --access-key-id $AKIARRVUR7R34QNBJF23 \
            --secret-access-key $imLProS211N441vqGtD4+fzB202IZkd9qsv64dSm
