name: CI/CD for AWS Lambda

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: lambda.py
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Package Lambda function
        run: |
          zip -r lambda_function.zip .

      - name: Configure AWS credentials
        run: |
          aws configure set aws_access_key_id "${{ secrets.AKIARRVUR7R3SIHCPP42 }}"
          aws configure set aws_secret_access_key "${{ secrets.4ov/MXj1Xfr+VdkCCuzYHH7HG+mXyfYq4VWxiqZV }}"
          aws configure set region ap-south-1

      - name: Deploy Lambda function
        run: |
          aws lambda update-function-code --function-name lambda_function --zip-file fileb://lambda_function.zip
